---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
hpi_df <- read_csv("data/hpi-tidy.csv")

world_df <- map_data("world")

world_full <- left_join(world_df, hpi_df, by = c("region" = "Country"))

```

##Exercise 1
```{r}
ggplot(data = world_full,
            mapping = aes(x = long, y = lat,
                          group = group)) +
  geom_polygon(colour = "black", aes(fill = Footprint)) +
  coord_map(projection = "mercator") +
  scale_fill_viridis_b()
```

##Exercise 2
```{r}
world_df <- world_df %>% mutate(region = if_else(region == "USA", "United States of America", region))

world_full <- left_join(world_df, hpi_df, by = c("region" = "Country"))

ggplot(data = world_full,
            mapping = aes(x = long, y = lat,
                          group = group)) +
  geom_polygon(colour = "black", aes(fill = Footprint)) +
  coord_map(projection = "mercator") +
  scale_fill_viridis_b()
```

##Exercise 3
```{r}
ggplot(data = world_full,
            mapping = aes(x = long, y = lat,
                          group = group)) +
  geom_polygon(colour = "black", aes(fill = Footprint)) +
  coord_map(projection = "mercator", xlim=c(-180,180)) +
  scale_fill_viridis_b()
```

##Exercise 4
The post says that greenland is 550% too big this is because mercator disproportionately makes things near the poles oo big and near the equator too small.

## Exercise 5
```{r}
ggplot(data = world_full,
            mapping = aes(x = long, y = lat,
                          group = group)) +
  geom_polygon(colour = "black", aes(fill = Footprint)) +
  coord_map(projection = "globular", xlim=c(-180,180)) +
  scale_fill_viridis_b()
```
Globualar and gilbert both make greenland much much smaller and africa much larger.

