s---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
## install.packages("palmerpenguins")
library(palmerpenguins)
library(tidyverse)
penguins

## single quantitative frequency plot
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_freqpoly() 
## single categorical barplot
ggplot(data = penguins, aes(x = species)) +
  geom_bar()
## two quant scatterplot
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point() +
  geom_smooth()
## two cat heatmap
ggplot(data = penguins, aes(x = species, y = island)) +
  geom_bin_2d()
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_histogram(colour = "black", fill = "white") +
  facet_wrap(~ species)
```


```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~ species)
ggplot(data = penguins, aes(x = species)) +
  geom_bar(stat = "count") ## don't need stat = "count" because it's the default.
ggplot(data = penguins, aes(x = species, fill = sex)) +
  geom_bar(position = "stack") + ## don't need "stacked" because it's default
  scale_fill_viridis_d()
ggplot(data = penguins, aes(x = species, fill = sex)) +
  geom_bar(position = "dodge")  ## don't need "stacked" because it's default

penguins_count<- penguins%>% group_by(species) %>%
  summarise(ncount = n())
ggplot(data = penguins_count, aes(x = species, fill = sex)) +
  geom_bar(position = "dodge")

  scale_fill_viridis_d()
ggplot(data = penguins, aes(x = species)) +
  geom_bar() +
  coord_polar()
ggplot(data = penguins, aes(x = species)) + 
  geom_bar() +
  coord_flip()
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm,
                            colour = species)) +
  geom_point() +
  geom_smooth()
```

```{r}
geom_boxplot(data = penguins)

ggplot(data = penguins, aes(x = bill_length_mm) ,color=species) +
  geom_freqpoly() 
```
#2
```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) ,color=species) +
  geom_freqpoly() 
```
#3
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm, colour = species)) +
  geom_point() +
  geom_smooth()
```
#4
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm))+
  geom_point(aes(colour = species)) +
  geom_smooth()
```
```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_histogram(colour = "black", fill = "white") +
  facet_wrap(~ species)
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~ species)
```
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm, colour = species)) +
  geom_point() +
  geom_smooth()
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm,
                            colour = species)) +
  geom_point() +
  geom_smooth() +
 theme(plot.background = element_rect(fill = "black"))
```
```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) + 
  geom_bar(position = "dodge") +
  facet_null()+
  geom_bar(stat = "count") +
  coord_flip() 
  
```
```{r}
library(tidyverse)
category <- rep(c("Group 1", "Group 2", "Group 3", "Group 4", "Group 5"), 7)
time <- rep(c(2000, 2001, 2002, 2003, 2004, 2005, 2006), each = 5) 
response <- rpois(length(category), 30)
df <- tibble(category, time, response)
ggplot(data = df, aes(x = time, y = response)) +
  geom_col(aes(fill = category)) +
  labs(y = "count") +
  scale_fill_viridis_d()
```

